@HotelListingApi_HostAddress = https://localhost:7120
###

GET {{HotelListingApi_HostAddress}}/api/hotels

###

@id=4
GET {{HotelListingApi_HostAddress}}/api/hotels/{{id}}

###

POST {{HotelListingApi_HostAddress}}/api/hotels
Content-Type: application/json

{
  "id": 4,
  "name": "Westin East",
  "address": "2102 Western Ave",
  "rating": 4.2
}

###

PUT {{HotelListingApi_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json

{
  "id": 2,
  "name": "Ocean View",
  "address": "123 Beach Ave",
  "rating": 4.9
}

###

DELETE {{HotelListingApi_HostAddress}}/api/hotels/{{id}}

###

GET {{HotelListingApi_HostAddress}}/api/countries

###

GET {{HotelListingApi_HostAddress}}/api/countries/{{id}}

###

POST {{HotelListingApi_HostAddress}}/api/countries
Content-Type: application/json

{
  //Country
}

###

PUT {{HotelListingApi_HostAddress}}/api/countries/{{id}}
Content-Type: application/json

{
  //Country
}

###

DELETE {{HotelListingApi_HostAddress}}/api/countries/{{id}}

###
